åç¨±ï¼šGitHub Actions æ¼”ç¤º
run-name: ${{ github.actor }} æ­£åœ¨æ¸¬è©¦ GitHub Actions ğŸš€
ä¸Šï¼š[æ¨]
å·¥ä½œï¼š
  æ¢ç´¢-GitHub-æ“ä½œï¼š
    é‹è¡Œï¼šubuntu-latest
    è…³æ­¥ï¼š
      - run: echo "ğŸ‰ è©²ä½œæ¥­æ˜¯ç”± ${{ github.event_name }} äº‹ä»¶è‡ªå‹•è§¸ç™¼çš„ã€‚"
      - run: echo "ğŸ§ æ­¤ä½œæ¥­ç¾åœ¨æ­£åœ¨ GitHub è¨—ç®¡çš„ ${{ runner.os }} ä¼ºæœå™¨ä¸ŠåŸ·è¡Œï¼"
      - run: echo "ğŸ” æ‚¨çš„åˆ†æ”¯åç¨±æ˜¯ ${{ github.ref }}ï¼Œæ‚¨çš„å„²å­˜åº«æ˜¯ ${{ github.repository }}ã€‚"
      - name: æŸ¥çœ‹å„²å­˜åº«ç¨‹å¼ç¢¼
        ä½¿ç”¨ï¼šactions/checkout@v4
      - run: echo "ğŸ’¡ ${{ github.repository }} å„²å­˜åº«å·²è¤‡è£½åˆ°åŸ·è¡Œå™¨ã€‚"
      - run: echo "ğŸ–¥ï¸ å·¥ä½œæµç¨‹ç¾åœ¨å·²æº–å‚™å¥½åœ¨é‹è¡Œå™¨ä¸Šæ¸¬è©¦æ‚¨çš„ç¨‹å¼ç¢¼ã€‚"
      - nameï¼šåˆ—å‡ºå„²å­˜åº«ä¸­çš„æ–‡ä»¶
        é‹è¡Œï¼š|
          ls ${{ github.workspace }}
      - run: echo "ğŸ This job's status is ${{ job.status }}."
